[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "folium>=0.18.0",
    "geopy>=2.4.1",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "streamlit-folium>=0.23.2",
    "streamlit>=1.40.2",
]
